include:
   - ./build/infra/infra.yaml
services:
  support_line:
    container_name: support_line
    build:
      context: .
      dockerfile: ./build/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "redis"